"""initial schema

Revision ID: 2923e9877995
Revises: 
Create Date: 2026-06-25 08:51:22.225183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2923e9877995'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('initial', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('tagFg', sa.String(), nullable=False),
    sa.Column('tagBg', sa.String(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('roleType', sa.String(), nullable=False),
    sa.Column('initial', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('modelType', sa.String(), nullable=False),
    sa.Column('tasks', sa.Integer(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('lastActive', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('roomsList', sa.JSON(), nullable=False),
    sa.Column('recentTasks', sa.JSON(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('lvl', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_months',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('m', sa.String(), nullable=False),
    sa.Column('v', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('initial', sa.String(), nullable=True),
    sa.Column('members', sa.Integer(), nullable=False),
    sa.Column('database', sa.String(), nullable=True),
    sa.Column('files', sa.String(), nullable=True),
    sa.Column('tasks', sa.JSON(), nullable=False),
    sa.Column('wfTotal', sa.Integer(), nullable=False),
    sa.Column('wfNote', sa.Text(), nullable=False),
    sa.Column('unread', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cron_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('expr', sa.String(), nullable=False),
    sa.Column('last', sa.String(), nullable=False),
    sa.Column('next', sa.String(), nullable=False),
    sa.Column('creator', sa.String(), nullable=False),
    sa.Column('creatorInitial', sa.String(), nullable=False),
    sa.Column('creatorColor', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('spark', sa.JSON(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('addr', sa.String(), nullable=False),
    sa.Column('os', sa.String(), nullable=False),
    sa.Column('cpu', sa.String(), nullable=False),
    sa.Column('cpuPct', sa.Integer(), nullable=False),
    sa.Column('ram', sa.String(), nullable=False),
    sa.Column('ramPct', sa.Integer(), nullable=False),
    sa.Column('gpu', sa.String(), nullable=False),
    sa.Column('gpuPct', sa.Integer(), nullable=False),
    sa.Column('vram', sa.String(), nullable=False),
    sa.Column('uptime', sa.String(), nullable=False),
    sa.Column('lastSeen', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('models', sa.JSON(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('by', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('ver', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('avatars', sa.JSON(), nullable=False),
    sa.Column('extra', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_servers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('transport', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('agents', sa.Integer(), nullable=False),
    sa.Column('calls24', sa.Integer(), nullable=False),
    sa.Column('lastSync', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('recentCalls', sa.JSON(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('taskId', sa.String(), nullable=True),
    sa.Column('cronId', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('initial', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('preview', sa.Text(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('unread', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('system', sa.Boolean(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('initial', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('modelType', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('tokens', sa.String(), nullable=False),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('initial', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('via', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assignee', sa.String(), nullable=False),
    sa.Column('initial', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('initial', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('twoFA', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('sessions', sa.JSON(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('triggerLabel', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('lastRun', sa.String(), nullable=False),
    sa.Column('runs24', sa.Integer(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('runs', sa.JSON(), nullable=False),
    sa.Column('runState', sa.String(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('authorName', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('avatarInitial', sa.String(), nullable=False),
    sa.Column('avatarColor', sa.String(), nullable=False),
    sa.Column('isAgent', sa.Boolean(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tasks')
    op.drop_table('signups')
    op.drop_table('session_logs')
    op.drop_table('rooms')
    op.drop_table('roles')
    op.drop_table('notifications')
    op.drop_table('mcp_servers')
    op.drop_table('knowledge_entries')
    op.drop_table('invites')
    op.drop_table('devices')
    op.drop_table('cron_jobs')
    op.drop_table('channels')
    op.drop_table('billing_months')
    op.drop_table('audit_log')
    op.drop_table('agents')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
